const goals = [
    {
        name:"3 six star dress",
        id: "3ssd",
        sixStarNewDress:3,
        newDress:0,
        sixStarNew:0,
        new:0,
    },
    {
        name:"2 six star dress",
        id: "2ssd",
        sixStarNewDress:2,
        newDress:0,
        sixStarNew:0,
        new:0,
    },
    {
        name:"1 six star dress",
        id: "1ssd",
        sixStarNewDress:1,
        newDress:0,
        sixStarNew:0,
        new:0,
    },
    {
        name:"3 dress",
        id: "3d",
        sixStarNewDress:0,
        newDress:3,
        sixStarNew:0,
        new:0,
    },
    {
        name:"2 dress",
        id: "2d",
        sixStarNewDress:0,
        newDress:2,
        sixStarNew:0,
        new:0,
    },
    {
        name:"1 dress",
        id: "1d",
        sixStarNewDress:0,
        newDress:1,
        sixStarNew:0,
        new:0,
    },
    {
        name:"3 six star new",
        id: "3ssn",
        sixStarNewDress:0,
        newDress:0,
        sixStarNew:3,
        new:0,
    },
    {
        name:"2 six star new",
        id: "2ssn",
        sixStarNewDress:0,
        newDress:0,
        sixStarNew:2,
        new:0,
    },
    {
        name:"1 six star new",
        id: "1ssn",
        sixStarNewDress:0,
        newDress:0,
        sixStarNew:1,
        new:0,
    },
    {
        name:"3 new",
        id: "3n",
        sixStarNewDress:0,
        newDress:0,
        sixStarNew:0,
        new:3,
    },
    {
        name:"2 new",
        id: "2n",
        sixStarNewDress:0,
        newDress:0,
        sixStarNew:0,
        new:2,
    },
    {
        name:"1 new",
        id: "1n",
        sixStarNewDress:0,
        newDress:0,
        sixStarNew:0,
        new:1,
    },
    {
        name:"2 six star dress 1 six star new",
        id: "2ssd1ssn",
        sixStarNewDress:2,
        newDress:0,
        sixStarNew:1,
        new:0,
    },
    {
        name:"2 six star dress 1 new",
        id: "2ssd1n",
        sixStarNewDress:2,
        newDress:0,
        sixStarNew:0,
        new:1,
    },
    {
        name:"2 dress 1 six star new",
        id: "2d1ssn",
        sixStarNewDress:0,
        newDress:2,
        sixStarNew:1,
        new:0,
    },
    {
        name:"2 dress 1 new",
        id: "2d1n",
        sixStarNewDress:0,
        newDress:2,
        sixStarNew:0,
        new:1,
    },
    {
        name:"1 six star dress 2 six star new",
        id: "1ssd2ssn",
        sixStarNewDress:1,
        newDress:0,
        sixStarNew:2,
        new:0,
    },
    {
        name:"1 six star dress 2 six star new",
        id: "1d2ssn",
        sixStarNewDress:0,
        newDress:1,
        sixStarNew:2,
        new:0,
    },
    {
        name:"1 six star dress 2 new",
        id: "1ssd2n",
        sixStarNewDress:1,
        newDress:0,
        sixStarNew:0,
        new:2,
    },
    {
        name:"1 dress 2 new",
        id: "1d2n",
        sixStarNewDress:0,
        newDress:1,
        sixStarNew:0,
        new:2,
    },
    {
        name:"1 dress 2 new",
        id: "1d2n",
        sixStarNewDress:0,
        newDress:1,
        sixStarNew:0,
        new:2,
    },
]

module.exports = goals;